# Site settings
title: UFZ Vislab Unity package
email: lars.bilke@ufz.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bilke.github.io/unity" # the base hostname & protocol for your site
twitter_username: larsbilke
github_username:  bilke

# Build settings
markdown: kramdown
